# compose.yaml

services:
  jenkins_controller:
    image: jenkins/jenkins:jdk21
    container_name: jenkins-controller
    restart: unless-stopped
    ports:
      #Jenkins service
      - "9100:8080" 
    volumes:
      # Working directory
      - jenkins-controller:/var/jenkins_home
    networks:
      - jenkins

  jenkins_agent:
    build: ./agent
    container_name: jenkins-agent
    depends_on: 
    - jenkins_controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    # Better signal forwarding for child processes
    init: true 
    privileged: true
    restart: unless-stopped
    # Documentation
    expose:
      - 22
    env_file:
      - ./.env
    environment:
    - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    networks:
      - jenkins
   
volumes:
  jenkins-controller:

networks:
  jenkins:
    name: jenkins
  
